#+TITLE: 100 Days Of Code - Log

* Day 0: October 05, 2018

** Today's Progress
+ Set up basic evironment
+ System: Mac Mojave
+ Editor: Emacs
+ Emacs dotfiles:
  
* Day 1: October 06, 2018

** Today's Progress
+ Finished Week one lessions video.
+ Set up Ocaml evironment with Emacs.
+ Write some basic ocaml code.
  
** Thoughts:
Ocaml is similar with Standard ML, And has lots of advantage.For example

The key additional ingredients
+ type inference: you don’t need to
write them!
+ pattern-matching: life saving data
manipulation feature!

In 2000 Jacques Garrigue’s extended Objective Label branch with
polymorphic methods, labeled and optional arguments, and polymorphic
variants, and In 2011 the name is definitely changed to Ocaml.

* Day 2: October 07, 2018

** Today's Progress
Read these materials.
[[http://palmstroem.blogspot.com/2012/05/lambda-calculus-for-absolute-dummies.html][The lanbda Calculus for Absolute Dummies]]
[[https://www.fun-mooc.fr/asset-v1:parisdiderot+56002+session03+type@asset+block/pdf_backus_turingaward_lecture.pdf][Can Programming Be Liberated from the von Neumann Style? A Functonal and ItsAlgebra of Programs]]

** Thoughts:
Turing Maching is designed for complicated calucations. It combing two parts ,
First is condition, Second is do, Just like If condition then do.


* Day 3: October 08, 2018 

** Today's Progress
+ Learn some basic ocaml syntax.
+ Read Real World Ocaml 
+ Try to install utop in Emacs, but not success
+ Write some notes about functional programming
  
** Thoughts:

 Why choose ocaml for learning.
 Beacuse, The learning curve of Ocaml is less than Haskell. and Ocaml is easy to
 work. For example, After finished ,I can choose Reasonml for further advance
 learning. Reasonml is created by Facebook, just like clojurescript,
 typescript.. Second Ocaml community is very nice to newbee, and As a Emacser
 can write ocaml than any other editor or IDE user. Third Ocaml is fu....ing insteresting. 

* Day 4: October 09, 2018

** Today's Progress
+ Read Real World Ocaml
+ Write somthing about Ocaml syntax
  
** Thoughts:

Programming languages have base types, like int, bool, and unit and 
Compound types.

+ “Each-of”: A compound type t describes values that contain each of values of type t1, t2, ..., and tn.
+ “One-of”: A compound type t describes values that contain a value of one of the types t1, t2, ..., or tn.
+ “Self-reference”: A compound type t may refer to itself in its definition in order to describe recursive data structures like lists and trees.
